version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: skakunma/kitygram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  frontend:
    image: skakunma/kitygram_frontend
    env_file: .env
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    image: skakunma/kitygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
